### ISSUE TITLE
Misleading test stub

### ISSUE THREAD

**Issue by gabrieleteotino** [moochin/GardenRover#3]
https://github.com/moochin/GardenRover/blob/1e668099d50cd698e51bb68f03667769db7a5db8/GardenRover.Tests/MowerTests.cs#L21-L24

The fact that the variable name changes from **mower** to **gardenRover** looks misleading to me.

**Comment by reub-the-cube** [comment]
Yeah I thought the same. I was just creating a PR for the rename and saw this!
#4
